import React from 'react'
import { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import jwt from "jsonwebtoken";
import Edit from "../components/profileFormComponent";

const KEY = 'azertyuiopqsdfghjklmwxcvbn';

const Editprofile: NextPage = () => {

  const [username, setUsername] = useState('');

  useEffect(() => {
    const token = localStorage.getItem('token');
    if (token) {
      const decodedToken = jwt.verify(token, KEY);
      if (typeof decodedToken !== 'string') {
        const username = decodedToken.username.charAt(0).toUpperCase() + decodedToken.username.slice(1);
        setUsername(username);
      }
    }
  }, []);

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className="flex flex-col items-center justify-center h-[90%] text-neutral-500">
          <div id="feedback-form">
          <h2 className="header">Edit your profile</h2>
          <div>
            <Edit/>
          </div>
        </div>
        </main>
    </>
  );
};

export default Editprofile;
