const options = [
  { label: 'HTML', value: 'HTML' },
  { label: 'CSS', value: 'CSS' },
  { label: 'JavaScript', value: 'JavaScript' },
  { label: 'React', value: 'React' },
  { label: 'Angular', value: 'Angular' },
  { label: 'Vue.js', value: 'Vue.js' },
  { label: 'Node.js', value: 'Node.js' },
  { label: 'Express', value: 'Express' },
  { label: 'Ruby on Rails', value: 'Ruby on Rails' },
  { label: 'Django', value: 'Django' },
  { label: 'Flask', value: 'Flask' },
  { label: 'ASP.NET', value: 'ASP.NET' },
  { label: 'PHP', value: 'PHP' },
  { label: 'Java', value: 'Java' },
  { label: 'Spring', value: 'Spring' },
  { label: 'Hibernate', value: 'Hibernate' },
  { label: 'Laravel', value: 'Laravel' },
  { label: 'Symfony', value: 'Symfony' },
  { label: 'CodeIgniter', value: 'CodeIgniter' },
  { label: 'Zend', value: 'Zend' },
  { label: 'Yii', value: 'Yii' },
  { label: 'ASP', value: 'ASP' },
  { label: 'JSP', value: 'JSP' },
  { label: 'Perl', value: 'Perl' },
  { label: 'Python', value: 'Python' },
  { label: 'TensorFlow', value: 'TensorFlow' },
  { label: 'PyTorch', value: 'PyTorch' },
  { label: 'Keras', value: 'Keras' },
  { label: 'Scikit-learn', value: 'Scikit-learn' },
  { label: 'OpenCV', value: 'OpenCV' },
  { label: 'Apache Spark', value: 'Apache Spark' },
  { label: 'Hadoop', value: 'Hadoop' },
  { label: 'AWS SageMaker', value: 'AWS SageMaker' },
  { label: 'Microsoft Azure ML', value: 'Microsoft Azure ML' },
  { label: 'Google Cloud AI Platform', value: 'Google Cloud AI Platform' },
  { label: 'IBM Watson', value: 'IBM Watson' },
  { label: 'Natural Language Processing (NLP)', value: 'Natural Language Processing (NLP)' },
  { label: 'Computer Vision', value: 'Computer Vision' },
  { label: 'Deep Learning', value: 'Deep Learning' },
  { label: 'Reinforcement Learning', value: 'Reinforcement Learning' },
  { label: 'Neural Networks', value: 'Neural Networks' },
  { label: 'GPT-3', value: 'GPT-3' },
  { label: 'AutoML', value: 'AutoML' },
  { label: 'Object Detection', value: 'Object Detection' },
  { label: 'Image Segmentation', value: 'Image Segmentation' },
  { label: 'Generative Adversarial Networks (GANs)', value: 'Generative Adversarial Networks (GANs)' },
  { label: 'Decision Trees', value: 'Decision Trees' },
  { label: 'Nmap', value: 'Nmap' },
  { label: 'Wireshark', value: 'Wireshark' },
  { label: 'Metasploit', value: 'Metasploit' },
  { label: 'Nessus', value: 'Nessus' },
  { label: 'Burp Suite', value: 'Burp Suite' },
  { label: 'Kali Linux', value: 'Kali Linux' },
  { label: 'Snort', value: 'Snort' },
  { label: 'Suricata', value: 'Suricata' },
  { label: 'Zeek', value: 'Zeek' },
  { label: 'OpenVAS', value: 'OpenVAS' },
  { label: 'OSSEC', value: 'OSSEC' },
  { label: 'Jenkins', value: 'Jenkins' },
  { label: 'GitLab', value: 'GitLab' },
  { label: 'GitHub Actions', value: 'GitHub Actions' },
  { label: 'Travis CI', value: 'Travis CI' },
  { label: 'CircleCI', value: 'CircleCI' },
  { label: 'TeamCity', value: 'TeamCity' },
  { label: 'Bamboo', value: 'Bamboo' },
  { label: 'Ansible', value: 'Ansible' },
  { label: 'Puppet', value: 'Puppet' },
  { label: 'Chef', value: 'Chef' },
  { label: 'SaltStack', value: 'SaltStack' },
  { label: 'Docker', value: 'Docker' },
  { label: 'Kubernetes', value: 'Kubernetes' },
  { label: 'Nomad', value: 'Nomad' },
  { label: 'Terraform', value: 'Terraform' },
  { label: 'AWS CloudFormation', value: 'AWS CloudFormation' },
  { label: 'Azure Resource Manager', value: 'Azure Resource Manager' },
  { label: 'Google Cloud Deployment Manager', value: 'Google Cloud Deployment Manager' },
  { label: 'React Native', value: 'React Native' },
  { label: 'Redux', value: 'Redux' },
  { label: 'Vuex', value: 'Vuex' },
  { label: 'Vue Router', value: 'Vue Router' },
  { label: 'AngularJS', value: 'AngularJS' },
  { label: 'RxJS', value: 'RxJS' },
  { label: 'NPM', value: 'NPM' },
  { label: 'Django REST Framework', value: 'Django REST Framework' },
  { label: 'Celery', value: 'Celery' },
  { label: 'Flask-RESTful', value: 'Flask-RESTful' },
  { label: 'Jinja2', value: 'Jinja2' },
  { label: 'ActiveRecord', value: 'ActiveRecord' },
  { label: 'RSpec', value: 'RSpec' },
  { label: 'Eloquent ORM', value: 'Eloquent ORM' },
  { label: 'Blade', value: 'Blade' },
  { label: 'Spring Boot', value: 'Spring Boot' },
  { label: 'Spring MVC', value: 'Spring MVC' },
  { label: 'Socket.io', value: 'Socket.io' },
  { label: 'Passport.js', value: 'Passport.js' },
  { label: 'Flask-RESTful', value: 'Flask-RESTful' },
  { label: 'Marshmallow', value: 'Marshmallow' },
  { label: 'Flask-SQLAlchemy', value: 'Flask-SQLAlchemy' },
  { label: 'Ruby Grape', value: 'Ruby Grape' },
  { label: 'Grape Entity', value: 'Grape Entity' },
  { label: 'Rack', value: 'Rack' },
  { label: 'Prisma', value: 'Prisma' },
  { label: 'GraphQL Nexus', value: 'GraphQL Nexus' },
  { label: 'TypeScript', value: 'TypeScript' },
  { label: 'Expo', value: 'Expo' }, 
];

export default options;